NAME	= ft_display_file
SRC		= ft_display_file.c
CC		= gcc
CFLAGS	= -Wall -Wextra -Werror
RM		= rm -f

all:
	${CC} ${CFLAGS} ${SRC} -o ${NAME}

clean:
	${RM} *.o

fclean: clean
	${RM} ${NAME}

.PHONY: all clean fclean
